# Make sure to check the documentation at https://goreleaser.com, https://goreleaser.com/customization/
project_name: mci
before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/simplelb/main.go
    hooks:
      post: ./upx.sh simplelb
    goarch:
      - amd64
env:
  - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
